spring.application.name=demo
server.port=8081
# Free user rate limit
rate-limit.free.capacity=5
rate-limit.free.refill-rate=0.083

# Paid user rate limit
rate-limit.paid.capacity=50
rate-limit.paid.refill-rate=0.83

# Default rate limit for unknown users
rate-limit.default.capacity=5
rate-limit.default.refill-rate=0.083